version: "3"
services:
  task_template:
    build:
      context: ./task_template
      dockerfile: Dockerfile_tangram_new
    ports:
      - 0.0.0.0:8070:8061
      - 8062:8062
    networks:
      - mynetwork
    environment:
      - SSL_CERTIFICATE=${SSL_CERTIFICATE}
      - SSL_KEY=${SSL_KEY}
    volumes:
      - ./certs/priv.key:/certificates/private.key
      - ./certs/ssl.cert:/certificates/certificate.crt      
    command: uvicorn main:app --port 8062 --host 0.0.0.0 --ssl-keyfile=/certificates/private.key --ssl-certfile=/certificates/certificate.crt
  model_template:
    build: ./model_template
    ports:
      - 0.0.0.0:8072:8061
    networks:
      - mynetwork
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  model_handler_template:
    build: ./model_handler_template
    ports:
      - 0.0.0.0:8071:8061
    networks:
      - mynetwork
    environment:
      - ATLAS_URI=${ATLAS_URI}
  orchestrator:
    depends_on:
      - task_template
      - model_template
      - model_handler_template
    build: ./orchestrator
    networks:
      - mynetwork
networks:
  mynetwork:
